name: subtitle_app
description: Video'dan altyazı çıkartan Flutter app
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true

